import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/nav-bar";
import { Footer } from "./components/footer";
import ToastProvider from "./components/toast-provider";

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-mulish",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.variable}`}>
        {" "}
        <ToastProvider />
        {children}
      </body>
    </html>
  );
}
